# Generated by Django 4.2.6 on 2024-04-01 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('detalles', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='unidad_medida_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('detalles', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(null=True)),
                ('telefono', models.PositiveBigIntegerField(null=True, unique=True)),
                ('imagen_perfil', models.ImageField(null=True, upload_to='vendedor_imgs/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('detalles', models.TextField(null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioUSD', models.DecimalField(decimal_places=2, default=80, max_digits=10)),
                ('slug', models.CharField(max_length=300, null=True, unique=True)),
                ('etiquetas', models.TextField(null=True)),
                ('imagen', models.ImageField(null=True, upload_to='product_imgs/')),
                ('cantidad', models.IntegerField()),
                ('estado_de_publicacion', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_productos', to='api.categoria_productos')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidad_medida_productos', to='api.unidad_medida_productos')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='imagenes_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(null=True, upload_to='product_imgs/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen_producto', to='api.producto')),
            ],
        ),
    ]
