# Generated by Django 4.2.6 on 2024-04-15 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_producto_estado_de_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='etiquetas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='slug',
        ),
    ]
